In [18]:
from scipy.optimize import linear_sum_assignment
import numpy as np

In [25]:
n = int(input("the number of doctor:"))
k = int( input("the number of hospital:"))
cap = int (input("the capacity of hospital:"))

the number of doctor:4
the number of hospital:3
the capacity of hospital:2


In [28]:
print(n, k, cap)

4 3 2


In [31]:
rate = []
a = []
for i in range(n):
    a = eval(input("enter my rate: "))
    rate.append(a)
print(rate)

enter my rate: 2,1,3
enter my rate: 3,2,1
enter my rate: 3,1,2
enter my rate: 1,3,2
[(2, 1, 3), (3, 2, 1), (3, 1, 2), (1, 3, 2)]


In [42]:
a = np.array(rate)
print(a)

[[2 1 3]
 [3 2 1]
 [3 1 2]
 [1 3 2]]


In [43]:

c = np.append(a,a, axis = 1)
print(c)

[[2 1 3 2 1 3]
 [3 2 1 3 2 1]
 [3 1 2 3 1 2]
 [1 3 2 1 3 2]]


In [44]:
count = k * cap - n

for i in range(count):
    c = np.row_stack((c,[4, 4, 4, 4, 4, 4]))
print(b)

[[2 1 3 2 1 3]
 [3 2 1 3 2 1]
 [3 1 2 3 1 2]
 [1 3 2 1 3 2]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [45]:
row_ind, col_ind = linear_sum_assignment(c)

In [46]:
print(c[row_ind, col_ind])

[1 1 1 1 4 4]


In [48]:
for i in range(n):
    print(col_ind[i]%k + 1)

2
3
2
1
